apiVersion: v2
name: keycloak-wrapper
description: Keycloak wrapper
type: application
version: 0.1.0

dependencies:
- name: keycloak
  version: "21.0.2"
  repository: "https://charts.bitnami.com/bitnami"
