keycloak:
  auth:
    existingSecret: "keycloak-secrets"
    passwordSecretKey: "admin-password"
  postgresql:
    auth:
      existingSecret: "keycloak-secrets"
      # key name is `postgres-password`
  global:
    compatibility:
      openshift:
        adaptSecurityContext: disabled # disable OpenShift specific security context adjustments