---

# ssh_keys
# A list of SSH keys of developers that require access to the deployment servers.
# eg.
# ssh_keys:
#   - ssh-rsa AAAAB.....
#   - ssh-ed25519 AAAAC.....
ssh_keys:
  # Govind
  - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGojMigbQwiqFGq4pU/2Z6Dz8NqhswLybdJoHgziQ2RR govind@nilenso.com
  # Hari
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCmcZAbL5HjMzZdFM/K8iFB7m/+Pn1HGeKMCu8CGClUAs1tSCNaWgZNHFrQaMHtf/m9lGEGUy9n3wI/CO3Ygy3SwNzNPhR9r+sDGZDp6LDEWKK2cYTMRQOU5N/g48ko0upK7hCPNd0cKRdDQpnKXgQDRh2x6KlrfcMlqxTBZUq0jLmkeQ+x0M8Hd+wkdvQfnDnfqfmG5NosJgzO6Ctyp04YQSw2zV0ue0wcMly5jjeikN+V9jUbI2jXygoh5JRGnzzC/0esSgn/g0QtDG0aUpwq9BEjhHxRHd+e0y7cutKrXRIdYMsikAye4oGndQ0Jv2A08kBn/dV82DrOL2qSG3VTgQv5mTEOOzX9icFLLc+P89LNOWu0O0MOeJCpKskO/6qfr/PXnqyipEI6D9wdwnMzNKj7ev7mGpy7fnQVHGnwABuZ2kkPE9hQqIjohFDGEsa1RpwabN4RY9s6q+nkysQHHX7J74G9a+k4O8ITzUGDj+5odQlhuP8ZHT9MfEiIen1A4nzDMgiMkGI3o4tX5FzXFwVYND1RgLaVmhiXxTGSS0viPxIXrwhiSlMs3sZIyuiZuv4MWRkq+emJaue8kyAnMJMRlOquhWFncmXcmsb5lSu3SxH+d+Bq8I/KZRr8VrwEEQkdBew9/UBsjwWdX1EqKEeC6FEXYtt5LrChjPAXIw== hari.mohanraj89@gmail.com
  # Prabhanshu
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCs7Uy4J2pY6HrSArnDM8CuHV9nXyXbl/8dv63HG1sZJW1Wzba5Tjr1ZWbXxWXDCwdy9dO/3MuDl7JN1wmIgRLm4gZTXlAv7lsREdlMDCh98PpUgU34ccqOPQSJo5YdwwMePBZVNjWTIRUZsWn30YrD6i+O+bVINNLXRrWaOZdJIh/aEmhrF0JRGuUAImPgTCSuA2eQjtOVQ03QLw+njax2H+069bDV70fnx4MvUQv6UdO5jfMYhFLcabgCoL+oyQ9ZHgOzp6iJNEBSM/ja1oXe8AGyq8zukN/jVX3OIDXXemGamDp6O22EIjamduErqkgjifPROInvUUA3hQST1rIN prabhanshu@MacBook-Pro-5.local
  # Priyanga
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCbSVbl4upFXBJxmhxn4CN7DKNL+Xdx+maVjdqIuY+p99bPaCfD5OqGJIVUa1RZutYaY0HO96NI8rSn2emfRBDtvXf3/WQgKc66mxUGUT0HWNgZ+jNsyV21xwqAmUfcsyNWyMX3Nst6WlL14je6paSsLHe09cIxuP+iaywY6sI8trwq27ObA3KpTKk+mQXKygTNPjhcOsHg9lLCyJzoItDDPZ6rPlcdUybxVb30GDzUjVmPLPbIatDJw7Idqho5aXGIznB7I2cyPEDH50gl1nydcI80tAUpEmXGzg2fIp2FTRWdMopQ1yiMvI7zB1HILmjQA+ZB6/QqKDQzmQBjTBDaLlZswDGG0Z0BdfRbIcjE03GXj7Ht6NDHr5e/nN88G0xIYlvYLoZ4Bpp1Y3XTowTQptXXl9fOcgUFqPgv/zFKlWvQNSmhg0J1B5bWCdTppJLCA1myCrFq/W1xx3/qef0GSwxrV/jsrlBh1ELS2IXiCE1+T/SjmKCIHT0d3C9XVdO633RR9rwRHmXbSiawqEHKw+LWT5AzefrUumP5GpPmAgcGR8hTss5UY67LOV9ECyc6wNP9NY9fvn+Z56VtYx2JyTeulUDZ6FquPAQuT2OwvAiMvjIEp6bMgIzN2dz0xbUvFac2k7/DCO/tsKj7WdqrXIMAUYKuHC/W4oIDFUBlCw== priyangapkini@Priyangas-MacBook-Air.local
  # Roy Peter
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC/rvmKX4AkkLbvazY9PmEyPosDOW461y7dhDW0Qkvv4fMLy7INimi0qGcoEfaxXAVT9eI3mi9axYWXogao2LHd5Y8LJP3SJAE+g4uDZkY0Omg2PMqtikNLLzjQQHsV0OgUfPs+Iv3ZaXtDqLY9AEwwCnWRRlaCW9R7G1H5+eZYpwwolDOyHIjoEC1j5IFkE0uDLjl5eookbQnIks5bWcKOZ/2052ZMIcCoI1nRj2Op7XefGO9V2n+k4A0k8TXjJg8ioZX4nqBtiJH6X2ofJtq9Ny77gOtjsupIA6w1PVsZuFNhJMiRSVUP/VPAug+Sf/o+yog16cWDiDmKTl1Xy73rfO50y3U9elDOrR/Me0YXDkqKXiFGjzp51rwLaldTgyjagJtB9Ldq9p13MKI5kT+tNiMQ5BEJWYtnieXrKVK+WL0zcWtduS2wU6Z7fvc5fVsmd0vpHTNj9ASxpcrEpRqwMtqSaELDMtpFEKZATxCQfDnryQfYWhHPos7wf7Ulj18= roypeter@r2d2
  # SemaphoreCI
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCt/h+ObkK2dDhFe07QCrH33D8ER79buKWzd1aH5cZPV73c6ffM4T7PQfC2RLQ+joEg7QxxZ20WKzOUudhtP+2jKeyIJ2pn7FahscrjM7Pd/OjgvZMgeXRHzeWDmwsd23F9yjepi2Gg6WKjjAqLHq4jUB84YBzrVXxAw99rwZwEicOpPMEbT8hJU67FSRHJr0B99+pqp9Zt4v7qqTWaoVOQML2MFVoJfZu7cm9nD/7K0SYsJgyCdALkMns6zhEmbaA8G2Wc928ivdyNDFShletYoq4B53kZPH4jWipQo7SVGo93krJtKDGtUHGgBk2llfF/fPRj7aO4lMVVPCf/CxzI22FuWqofkeIbwOELpPmi5uhB+DchGQhP23cbaEUdfEA/jewpubQZG7+HqWTZbGSLD0f63UhkB+WaIw1XnW8VG4U55zJJ8jWlJZYHsqkCIY+tV0XPpDfyGNaUmWd5+Taboa/cES/AKdwgdBP/VCcbnexOKMiXnIEbXQfk06IQwIGZlR5mYCB5ZYYjuwqLrCIyYYDlNcFh+fLO/Dxkd2uZo3M2WZuuEmiUG3MvDAHIuMnrV4eqgYGbrLKYbhS2UTfe5mv1vPjCmJWk+NE2vVKMw7PKkE6hYSglikR+hplXVHE1Ep5eK1dMjsdmY4QglFzKdpehJsSrggn7u8PMbkp+aQ== semaphore@simple.org

# Set ec2 specific network interface
ansible_private_network_interface: "ansible_ens160"

# k3s
k3s_agent:
  flannel-iface: "ens160" # Use private ip networking interface for k3s clustering.
  node-label: "{{ k3s_node_labels }}"

k3s_server:
  flannel-iface: "ens160" # Use private ip networking interface for k3s clustering.
  write-kubeconfig-mode: "644" # Set kubeconfig file permission to 644.
  disable:
  - traefik # Disable traefik ingress controller.
  node-label: "{{ k3s_node_labels }}"
