#apiVersion: bitnami.com/v1alpha1
#kind: SealedSecret
#metadata:
#  creationTimestamp: null
#  name: datadog
#  namespace: datadog
#spec:
#  encryptedData:
#    api-key: AgCEq+k53+acVgDganaHX4vxqPGyOkkJ1zii1uYgSACjbaHWNm8OWQ1OSB1W+kjDvyb/wpt4IgkTSybHNc5ZSiFP7pb67wHtaZSoeMYpajyU82nbo+y0OkhCngQ6cFhAmj+MrQ+ogOL2Pm/wHO9nBBzZsuC37D2ybSbC0TZa4qn9FtVQE3XTx4rPH6xcbV5MhoBH6tSv5mxSDDrGsi4GwLPbeVnx33t/a1aeb9e2qsw/RUdfpLUQTiXpwCyQD/S5z2E4vnZODURQIh7oGS8uwu2BmEfDqVnG9zpK7JHlaJlY0CK8MP9w2AxOZfUpkp1+jEzqmzCropyCq4/wAG+9A/rXZ0GhkPCccPUsR6S9Pj5fAUp1heR97wZgKJI/KHUDSc+YDC+IL0DzYkaMxfa2vRGT+J/jkC201Hys57Sq2laeQEv8i6VwxgkrabD6F+akeqNqKXQGs4bgjuF8/CMrZ4u5d+4mIbK/73xP3M6GL1fsJdTK89WMRI4wwuKuFKiFCyWymfK+1P2X56MIuF2ptmGYzc7reTyo06SqWz2FQ0q+WmVL6zFE//Q0KtPvTfs58fclMawOUwQaRwwgoVniucpJp/6eQ0X6GLDAvLTILaWY+riqFln6IdTkhjYJjtL/qe4ss3Uhj0g2AUPxnkEitgps9Xpa7XeSrIwUompP2aeyvCnOA81+RNLzTzxDnl9aWSlHCZUQ/gj5UXHgeISfGeJqT8HUHvRk07cb8Rh8BkV8+A==
#    app-key: AgCIOvM6s9U1JkdRLFxdNB+ZDaxy4K6Awc43aZBYX9fAzEJgQG3x3eFlGljlOOAvEq94icufsT6NgRJOwWUMqpBUFFa0KX6+rXdyzexkI5uCd4URKHcXA/M1dOcO4LtTQBNeXiIW1S5D1Jj4QBXenBmAKNZUdVCYeFpknaZt/KzLU7AWqD7gn8f7G0AHDiiWuOP1pa7ece+u4pWvGtskDz4irZOd25DH9IU14GgD7xJ9TPEkNDuVT3HNy8rDIi7xHQslbdJWfy21NlM0vJGpdjVFRtq29fttdYxGC90Mbqf8MZi/UG+wJ/8XwQFfomXEximxhjILDWOCtDjX592iomMVf9ROf5ZN2W5id/zEBseONR6TNrcQ/VEtZSCTikVqX6x0LtKthJh+oe8x9ay8kP/GrsJAM1IdXURNpiWxzUBu9pYdIn/tETipY4Xi1krMRa5Oai3L16P3MznXMoyNWuMqQGBWYUNLhmbw080v68gDazrOO2YP/WGEGNrw2RyDeu0jtzHJjI4U5D8bEVAJLMDlyx7HTzTLv2Qchu5h2tysvupo3uCKU+0nfF5pIePZptd3EMczj3zL9UUnahifRnhto3dIgv7WMCEKMu0n0IXyPN1RUAfb/1QzTvz03WlB435MZxhn/IKT1HuzncmyL6oNOg3L8eIMXSqj/LXg72L3HXkt5xOTqD+KIl1ZSyN+hJOBZi9/DEgF890okvoJVp9n58LYX5RHXglZxWT4RskzdKQgVGcH9T2b
#  template:
#    metadata:
#      creationTimestamp: null
#      name: datadog
#      namespace: datadog
#    type: Opaque
#
