apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: simple-server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: simple-server
    spec:
      containers:
      - name: simple-server
        image: {{ .Values.image }}
        args: ["bin/rails", "server",  "-b", "0.0.0.0"]
        envFrom:
          - secretRef:
              name: {{ .Values.secret_name }}
          - configMapRef:
              name: {{ .Values.configmap_name }}
        env:
          - name: SIMPLE_SERVER_DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.db_secret.name }}
                key: {{ .Values.db_secret.key }}
                optional: false
