apiVersion: v1
kind: ConfigMap
metadata:
  name: simple-server
  namespace: simple-v1
data:
  ANALYTICS_DASHBOARD_CACHE_TTL: "60"
  ANALYTICS_TIME_ZONE: ""
  APPOINTMENT_NOTIFICATION_FAN_OUT_BATCH_SIZE: ""
  APPOINTMENT_NOTIFICATION_HOUR_OF_DAY_FINISH: "12"
  APPOINTMENT_NOTIFICATION_HOUR_OF_DAY_START: "8"
  CALL_SESSION_REDIS_HOST: "redis-master"
  CALL_SESSION_REDIS_POOL_SIZE: "17"
  CALL_SESSION_REDIS_TIMEOUT_SEC: "1"
  CRON_TIME_ZONE: ""
  DATADOG_ENABLED: "true"
  DEFAULT_COUNTRY: "IN"
  DEFAULT_NUMBER_OF_RECORDS: "10"
  DEFAULT_TIME_ZONE: ""
  DHIS2_VERSION: "2.28"
  EMAIL_SUBJECT_PREFIX: ""
  EXOTEL_API_RATE_LIMIT_PER_MINUTE: "250"
  EXOTEL_RE_REQUEST_WHITELIST_MONTHS: "6"
  EXOTEL_UPDATE_PHONE_NUMBER_DETAILS_BATCH_SIZE: "1000"
  EXOTEL_WHITELIST_PHONE_NUMBER_DETAILS_BATCH_SIZE: "1000"
  EXPORT_AUDIT_LOGS_BATCH_SIZE: "5000"
  HELP_SCREEN_YOUTUBE_PASSPORT_URL: "https://youtu.be/aktZ1yTdDOA"
  HELP_SCREEN_YOUTUBE_TRAINING_URL: "https://youtu.be/MC_45DoRw2g"
  HELP_SCREEN_YOUTUBE_VIDEO_URL: "https://youtu.be/zthrk6XfpjQ"
  PROGRAM_INCEPTION_DATE: "2018-01-01"
  RAILS_CACHE_REDIS_URL: "redis://redis-master:6379/0"
  SENTRY_CURRENT_ENV: "qa"
  SIDEKIQ_CONCURRENCY: "10"
  SIDEKIQ_REDIS_POOL_SIZE: "20"
  SIDEKIQ_REDIS_HOST: "worker-redis-master"
  SIMPLE_SERVER_DATABASE_NAME: "simple"
  SIMPLE_SERVER_DATABASE_HOST: "simple-primary"
  SIMPLE_SERVER_DATABASE_USERNAME: "simple"
  SIMPLE_SERVER_ENV: "todo"
  SIMPLE_SERVER_HOST: "api.lk.simple.org"
  SIMPLE_SERVER_HOST_PROTOCOL: "https"
  TEMPORARY_RETENTION_DURATION_SECONDS: "60"
  USER_OTP_SMS_DELAY_IN_SECONDS: "5"
  USER_OTP_VALID_UNTIL_DELTA_IN_MINUTES: "5"
  DD_AGENT_HOST: "datadog-agent-agent.datadog"
  LOG_ARCHIVE_S3_PATH_PREFIX: "todo"
