apiVersion: v1
kind: ConfigMap
metadata:
  name: simple-server
  namespace: simple-v1
data:
  ANALYTICS_DASHBOARD_CACHE_TTL: "7200"
  ANALYTICS_TIME_ZONE: "Asia/Colombo"
  APPOINTMENT_NOTIFICATION_FAN_OUT_BATCH_SIZE: "200"
  APPOINTMENT_NOTIFICATION_HOUR_OF_DAY_FINISH: "16"
  APPOINTMENT_NOTIFICATION_HOUR_OF_DAY_START: "10"
  CALL_SESSION_REDIS_HOST: ""
  CALL_SESSION_REDIS_POOL_SIZE: ""
  CALL_SESSION_REDIS_TIMEOUT_SEC: ""
  CRON_TIME_ZONE: "Asia/Colombo"
#  DATADOG_ENABLED: "false"
  DEFAULT_COUNTRY: "LK"
  DEFAULT_NUMBER_OF_RECORDS: "100"
  DEFAULT_TIME_ZONE: "Asia/Colombo"
  DHIS2_VERSION: ""
  EMAIL_SUBJECT_PREFIX: "[Simple Sri Lanka] "
  EXOTEL_API_RATE_LIMIT_PER_MINUTE: ""
  EXOTEL_CALL_DETAILS_JOB_RETRY_SECONDS: ""
  EXOTEL_CALL_DETAILS_JOB_RETRY_TIMES: ""
  EXOTEL_RE_REQUEST_WHITELIST_MONTHS: ""
  EXOTEL_UPDATE_PHONE_NUMBER_DETAILS_BATCH_SIZE: ""
  EXOTEL_WHITELIST_PHONE_NUMBER_DETAILS_BATCH_SIZE: ""
  EXPORT_AUDIT_LOGS_BATCH_SIZE: ""
  HELP_SCREEN_YOUTUBE_PASSPORT_URL: "https://youtu.be/aktZ1yTdDOA"
  HELP_SCREEN_YOUTUBE_TRAINING_URL: "https://youtu.be/MC_45DoRw2g"
  HELP_SCREEN_YOUTUBE_VIDEO_URL: "https://youtu.be/YjfPCUtZHlI"
  PROGRAM_INCEPTION_DATE: "2021-08-01"
  RAILS_CACHE_REDIS_URL: "redis://cache-redis-master:6379/0"
  RAILS_MAX_THREADS: "20"
  RAILS_LOG_LEVEL: "error"
  REPORT_ENUMERATOR_BATCH_SIZE: "1000"
  SENTRY_CURRENT_ENV: "production"
  SENTRY_SAMPLE_RATE: "0.33"
  SIDEKIQ_CONCURRENCY: "10"
  SIDEKIQ_REDIS_POOL_SIZE: "20"
  SIDEKIQ_REDIS_HOST: "worker-redis-master"
  SIMPLE_SERVER_DATABASE_NAME: "simple_db_sri_lanka_production_001"
  SIMPLE_SERVER_DATABASE_HOST: "simple-primary"
  SIMPLE_SERVER_DATABASE_USERNAME: "simple"
  SIMPLE_SERVER_ENV: "production"
  SIMPLE_SERVER_HOST: "api-simple.health.gov.lk"
  SIMPLE_SERVER_HOST_PROTOCOL: "https"
  STALE_EXPERIMENT_MIN_DAYS_SINCE_LAST_VISIT: "35"
  STALE_EXPERIMENT_MAX_DAYS_SINCE_LAST_VISIT: "365"
  TEMPORARY_RETENTION_DURATION_SECONDS: "86400"
  USER_OTP_SMS_DELAY_IN_SECONDS: "5"
  USER_OTP_VALID_UNTIL_DELTA_IN_MINUTES: "360"
 # DD_AGENT_HOST: "datadog-agent-agent.datadog"
  RAILS_ENV: "production"
