apiVersion: v1
kind: Service
metadata:
  name: prometheus-pushgateway
  labels:
    app.kubernetes.io/name: prometheus-pushgateway
    prometheus.io/app: prometheus-pushgateway
spec:
  type: ClusterIP
  ports:
  - name: metrics
    port: {{ .Values.service.port }}
    targetPort: 9091
    protocol: TCP
  selector:
    app.kubernetes.io/name: prometheus-pushgateway
