apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus-pushgateway
  labels:
    app.kubernetes.io/name: prometheus-pushgateway
    prometheus.io/app: prometheus-pushgateway
spec:
  jobLabel: prometheus-pushgateway
  endpoints:
  - port: metrics
    interval: 30s
    honorLabels: true
  selector:
    matchLabels:
      app.kubernetes.io/name: prometheus-pushgateway
