apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: datadog
  namespace: datadog
spec:
  encryptedData:
    api-key: AgAv+f+lbgbVYz5lBo/UwABgiiD2TECzx3tf1iroDjgZOXjm9ev771R8bQQZhFl+qoIsu6rnHHnJKz4p98gOOr4Shs9nmyTEkfrgWIaTtJA3wqR85ZZHD4Zx6GSBpL7FaFN9d3UzRVlOhrI4vAS/ANd91gz1z7pND9gITmNY8z2B+OfHsqwm4LMUYJUQ3f8ZDr6LhVdP2zxdTkr0QGzazPi/A1L7D3T60kFyQGcntZ8yuqdy6hEofe7F7SE/1cNA+xqaqzk81M/TfGA7cuEy1HViSqKB6XRp2TfUzTctHcRWmOrln6wJSC6V/A596VDz1mvwrO2aAzAHJQB/+z8GQElxYS5vwfuzxobr71ecxqINcLvf7FdA64TkGczbXZBdbdJFwGXs+fx/ekugUJgply8PI+n/RC0P/x6qZa9OZEs1Wp0KR959L5kGfvsjXWOMIOikD1I6iNZDGem3xWgdagU6N3c2ACQW51Nz2zvNKyg5EX3pFE21L2hBgsaJVpaPuILC3IIoDA/TGCb4Aky/Txz+XBm1/rmStZnEgcf2ms/rdn+C4lFEQAhC47uyVkN4MHXTUAsFV43SjJEyj8VwMIVK++1PD/0b1kZeOsUPQa8/SmoHEhjQ260IyJe/QAVgj/3hCy9b+3k28oH9m0LY+Le7rRlNq0MoDjkx/Fdi7zQk8OHOgI9oz5bTpzNoytKmmBSmCZpnws1CnLLI4XzwuO3nbnZHofLq7dRkqR9DiXSLjw==
    app-key: AgB1V8rQRSf+XyJyF1rZJrOD34NdfE42R7izD/aHQNgF4DphCMiOh7OArPbZvzSHCUAO2vy85dOfXqo6XPQGS1eZspQEIIv9bm4kRoDeQnIvbBfCI430TQ+E3WAE8M0rHmB2r1DfHwr1j7zQk0I9IpPJowxuBAOSFlTbLP2QsACH+d2Ul5O1WTwYIdvdSP2UVssUDTtsxQckP1HV91r1GJjxg4Hi09DjEz/S30OQrGCEUnhiH2kC0wibHfvGPsK/V841lrzhT9MTPYzWoQ77C3IiECp32jsUefepqVTOglcbz31x/IJOGxbWTapBBEcyTzsP3e6JbxqVxvjtaEkCe/njo5t/S+u6rGB235uCmtjqT2yzJq2PsbugzA7JIzOMzMuqHihI8uhdxECcZq3dLruwB96RkySEwa/yQtS/FKBdxLPJvJE8AYxKONFumtC3blO/xYMlycY9Q1BSP6q3xNnVBS8lgWqntFx1l40MTaBdTczqMfaU6f3AnQqizT1PUOEzzrKMApGNHftNno2aWLtCziuBUjaTzA411SYXMw+zoysgcNwAW3tQiIQmEj3nKdM7F4EOHIWlD86gz/KDp12dGuUw8Aw35K44iCFTOZkO5QateuiPIdTFlfK309V1sQTIFaUoRY59PYV7imve0zdGA2vH+OZ/4gt8tzw2fnWk65LK73xusOBY7ofpzmkF83b8V6TuwRiuTbAUqLq2dmFSgYNOUBQOa4Mr1TkXYyQ2/qsLkV3F5wi+
  template:
    metadata:
      creationTimestamp: null
      name: datadog
      namespace: datadog
    type: Opaque

