apiVersion: v1
kind: ConfigMap
metadata:
  name: simple-server
  namespace: simple-v1
data:
  ANALYTICS_TIME_ZONE: 'Asia/Kolkata'
  ANALYTICS_DASHBOARD_CACHE_TTL: "172800"
  APPOINTMENT_NOTIFICATION_FAN_OUT_BATCH_SIZE: "500"
  APPOINTMENT_NOTIFICATION_HOUR_OF_DAY_FINISH: "12"
  APPOINTMENT_NOTIFICATION_HOUR_OF_DAY_START: "8"
  CALL_SESSION_REDIS_HOST: "worker-redis-master"
  CALL_SESSION_REDIS_POOL_SIZE: "12"
  CALL_SESSION_REDIS_TIMEOUT_SEC: "1"
  CRON_TIME_ZONE: "Asia/Kolkata"
  CPHC_SIDEKIQ_QUEUE: "cphc_migration"
  DATADOG_ENABLED: "false"
  DEFAULT_COUNTRY: "IN"
  DEFAULT_NUMBER_OF_RECORDS: "10000"
  DEFAULT_TIME_ZONE: "Asia/Kolkata"
  DHIS2_DATA_ELEMENTS_FILE: "config/data/dhis2/sandbox.yml"
  DHIS2_VERSION: "2.28"
  EMAIL_SUBJECT_PREFIX: "[SANDBOX] "
  EXOTEL_API_RATE_LIMIT_PER_MINUTE: "250"
  EXOTEL_CALL_DETAILS_JOB_RETRY_SECONDS: "600"
  EXOTEL_CALL_DETAILS_JOB_RETRY_TIMES: "5"
  EXOTEL_RE_REQUEST_WHITELIST_MONTHS: "6"
  EXOTEL_UPDATE_PHONE_NUMBER_DETAILS_BATCH_SIZE: "1000"
  EXOTEL_WHITELIST_PHONE_NUMBER_DETAILS_BATCH_SIZE: "1000"
  EXPORT_AUDIT_LOGS_BATCH_SIZE: "5000"
  HELP_SCREEN_YOUTUBE_PASSPORT_URL: "https://youtu.be/aktZ1yTdDOA"
  HELP_SCREEN_YOUTUBE_TRAINING_URL: "https://youtu.be/MC_45DoRw2g"
  HELP_SCREEN_YOUTUBE_VIDEO_URL: "https://youtu.be/zthrk6XfpjQ"
  PROGRAM_INCEPTION_DATE: "2018-01-01"
  RAILS_CACHE_REDIS_URL: "redis://cache-redis-master:6379/0"
  RAILS_MAX_THREADS: "20"
  RAILS_LOG_LEVEL: "error"
  REFRESH_WORK_MEM: "1GB"
  REPORT_ENUMERATOR_BATCH_SIZE: "1000"
  SENTRY_CURRENT_ENV: "sandbox"
  SENTRY_SAMPLE_RATE: "0.1"
  SIDEKIQ_CONCURRENCY: "15"
  SIDEKIQ_REDIS_POOL_SIZE: "20"
  SIDEKIQ_REDIS_HOST: "worker-redis-master"
  SIMPLE_SERVER_DATABASE_NAME: "simple_db_development_sandbox_001"
  SIMPLE_SERVER_DATABASE_HOST: "simple-primary"
  SIMPLE_SERVER_DATABASE_USERNAME: "simple"
  SIMPLE_SERVER_ENV: "sandbox"
  SIMPLE_SERVER_HOST: "api-sandbox.simple.org"
  SIMPLE_SERVER_HOST_PROTOCOL: "https"
  STALE_EXPERIMENT_MIN_DAYS_SINCE_LAST_VISIT: "35"
  STALE_EXPERIMENT_MAX_DAYS_SINCE_LAST_VISIT: "365"
  TEMPORARY_RETENTION_DURATION_SECONDS: "3600"
  USER_OTP_SMS_DELAY_IN_SECONDS: "5"
  USER_OTP_VALID_UNTIL_DELTA_IN_MINUTES: "360"
  DD_AGENT_HOST: "datadog-agent-agent.datadog"
